
package com.sinosoft.framework.agri.core.gycore.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GYCoreWebService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://36.32.160.60:9000/GYCoreWebService.asmx?WSDL")
public class GYCoreWebService
    extends Service
{

    private final static URL GYCOREWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException GYCOREWEBSERVICE_EXCEPTION;
    private final static QName GYCOREWEBSERVICE_QNAME = new QName("http://tempuri.org/", "GYCoreWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://36.32.160.60:9000/GYCoreWebService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GYCOREWEBSERVICE_WSDL_LOCATION = url;
        GYCOREWEBSERVICE_EXCEPTION = e;
    }

    public GYCoreWebService() {
        super(__getWsdlLocation(), GYCOREWEBSERVICE_QNAME);
    }

    public GYCoreWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GYCOREWEBSERVICE_QNAME, features);
    }

    public GYCoreWebService(URL wsdlLocation) {
        super(wsdlLocation, GYCOREWEBSERVICE_QNAME);
    }

    public GYCoreWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GYCOREWEBSERVICE_QNAME, features);
    }

    public GYCoreWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GYCoreWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GYCoreWebServiceSoap
     */
    @WebEndpoint(name = "GYCoreWebServiceSoap")
    public GYCoreWebServiceSoap getGYCoreWebServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "GYCoreWebServiceSoap"), GYCoreWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GYCoreWebServiceSoap
     */
    @WebEndpoint(name = "GYCoreWebServiceSoap")
    public GYCoreWebServiceSoap getGYCoreWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "GYCoreWebServiceSoap"), GYCoreWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GYCOREWEBSERVICE_EXCEPTION!= null) {
            throw GYCOREWEBSERVICE_EXCEPTION;
        }
        return GYCOREWEBSERVICE_WSDL_LOCATION;
    }

}
