
package com.sinosoft.framework.agri.core.gycore.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GYCoreWebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GYCoreWebServiceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.HelloWorldResponse")
    public String helloWorld();

    /**
     * 获取用户权限行政区划
     * 
     * @param userCode
     * @param parentID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getUserRegion")
    @WebResult(name = "getUserRegionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getUserRegion", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.GetUserRegion")
    @ResponseWrapper(localName = "getUserRegionResponse", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.GetUserRegionResponse")
    public String getUserRegion(
            @WebParam(name = "userCode", targetNamespace = "http://tempuri.org/")
                    String userCode,
            @WebParam(name = "parentID", targetNamespace = "http://tempuri.org/")
                    String parentID);

    /**
     * 获取用户所有行政区划权限
     * 
     * @param userCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getUserAllRegion")
    @WebResult(name = "getUserAllRegionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getUserAllRegion", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.GetUserAllRegion")
    @ResponseWrapper(localName = "getUserAllRegionResponse", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.GetUserAllRegionResponse")
    public String getUserAllRegion(
            @WebParam(name = "userCode", targetNamespace = "http://tempuri.org/")
                    String userCode);

    /**
     * 新增承保节点数据
     * 
     * @param insureListCode
     * @param nodeItemXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/addNodeItemData")
    @WebResult(name = "addNodeItemDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "addNodeItemData", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.AddNodeItemData")
    @ResponseWrapper(localName = "addNodeItemDataResponse", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.AddNodeItemDataResponse")
    public String addNodeItemData(
            @WebParam(name = "insureListCode", targetNamespace = "http://tempuri.org/")
                    String insureListCode,
            @WebParam(name = "nodeItemXml", targetNamespace = "http://tempuri.org/")
                    String nodeItemXml);

    /**
     * 更新客户及银行基本信息
     * 
     * @param customerinfoXML
     * @param customerType
     * @param customerCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/updateCustomerInfo")
    @WebResult(name = "updateCustomerInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateCustomerInfo", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.UpdateCustomerInfo")
    @ResponseWrapper(localName = "updateCustomerInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.UpdateCustomerInfoResponse")
    public String updateCustomerInfo(
            @WebParam(name = "customerCode", targetNamespace = "http://tempuri.org/")
                    String customerCode,
            @WebParam(name = "customerType", targetNamespace = "http://tempuri.org/")
                    String customerType,
            @WebParam(name = "customerinfoXML", targetNamespace = "http://tempuri.org/")
                    String customerinfoXML);

    /**
     * 生成预报案
     * 
     * @param readyRegistInfoXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/addReadyRegistInfo")
    @WebResult(name = "addReadyRegistInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "addReadyRegistInfo", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.AddReadyRegistInfo")
    @ResponseWrapper(localName = "addReadyRegistInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.AddReadyRegistInfoResponse")
    public String addReadyRegistInfo(
            @WebParam(name = "readyRegistInfoXML", targetNamespace = "http://tempuri.org/")
                    String readyRegistInfoXML);

    /**
     * 增加报案
     * 
     * @param registInfoXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/addRegistInfo")
    @WebResult(name = "addRegistInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "addRegistInfo", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.AddRegistInfo")
    @ResponseWrapper(localName = "addRegistInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.AddRegistInfoResponse")
    public String addRegistInfo(
            @WebParam(name = "registInfoXML", targetNamespace = "http://tempuri.org/")
                    String registInfoXML);

    /**
     * 修改密码
     * 
     * @param userPwd
     * @param userCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/updateUsePwd")
    @WebResult(name = "updateUsePwdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateUsePwd", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.UpdateUsePwd")
    @ResponseWrapper(localName = "updateUsePwdResponse", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.UpdateUsePwdResponse")
    public String updateUsePwd(
            @WebParam(name = "userCode", targetNamespace = "http://tempuri.org/")
                    String userCode,
            @WebParam(name = "userPwd", targetNamespace = "http://tempuri.org/")
                    String userPwd);

    /**
     * 更新预投保单号于保单关联
     * 
     * @param insurancePolicyNo
     * @param listCode
     * @param insuranceListCode
     * @param policyNo
     * @param batchPolicyNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/updateListRefPolicy")
    @WebResult(name = "updateListRefPolicyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateListRefPolicy", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.UpdateListRefPolicy")
    @ResponseWrapper(localName = "updateListRefPolicyResponse", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.UpdateListRefPolicyResponse")
    public String updateListRefPolicy(
            @WebParam(name = "insuranceListCode", targetNamespace = "http://tempuri.org/")
                    String insuranceListCode,
            @WebParam(name = "insurancePolicyNo", targetNamespace = "http://tempuri.org/")
                    String insurancePolicyNo,
            @WebParam(name = "policyNo", targetNamespace = "http://tempuri.org/")
                    String policyNo,
            @WebParam(name = "batchPolicyNo", targetNamespace = "http://tempuri.org/")
                    String batchPolicyNo,
            @WebParam(name = "listCode", targetNamespace = "http://tempuri.org/")
                    String listCode);

    /**
     * 清单补录
     * 
     * @param listDataXml
     * @param insureListCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/addListAdditionalData")
    @WebResult(name = "addListAdditionalDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "addListAdditionalData", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.AddListAdditionalData")
    @ResponseWrapper(localName = "addListAdditionalDataResponse", targetNamespace = "http://tempuri.org/", className = "com.sinosoft.framework.agri.core.gycore.client.AddListAdditionalDataResponse")
    public String addListAdditionalData(
            @WebParam(name = "insureListCode", targetNamespace = "http://tempuri.org/")
                    String insureListCode,
            @WebParam(name = "listDataXml", targetNamespace = "http://tempuri.org/")
                    String listDataXml);

}
