
package com.sinosoft.agriprpall.api.client.platformclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgriPrpallPlatformService", targetNamespace = "http://server.webservice.indiv.sinosoft.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgriPrpallPlatformService {


    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getPropertyReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "getProperty", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.GetProperty")
    @ResponseWrapper(localName = "getPropertyResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.GetPropertyResponse")
    public String getProperty(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getRuleInUtiPlatConfigRuleReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "getRuleInUtiPlatConfigRule", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.GetRuleInUtiPlatConfigRule")
    @ResponseWrapper(localName = "getRuleInUtiPlatConfigRuleResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.GetRuleInUtiPlatConfigRuleResponse")
    public String getRuleInUtiPlatConfigRule(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getRiskTaxRateReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "getRiskTaxRate", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.GetRiskTaxRate")
    @ResponseWrapper(localName = "getRiskTaxRateResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.GetRiskTaxRateResponse")
    public String getRiskTaxRate(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

}
