
package com.sinosoft.agriprpall.api.client.platformclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgriPrpallPlatformService", targetNamespace = "http://server.webservice.indiv.sinosoft.com", wsdlLocation = "http://192.168.0.136:7001/webAgriPrpallService/services/AgriPrpallPlatformService?wsdl")
public class AgriPrpallPlatformService_Service
    extends Service
{

    private final static URL AGRIPRPALLPLATFORMSERVICE_WSDL_LOCATION;
    private final static WebServiceException AGRIPRPALLPLATFORMSERVICE_EXCEPTION;
    private final static QName AGRIPRPALLPLATFORMSERVICE_QNAME = new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallPlatformService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.136:7001/webAgriPrpallService/services/AgriPrpallPlatformService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGRIPRPALLPLATFORMSERVICE_WSDL_LOCATION = url;
        AGRIPRPALLPLATFORMSERVICE_EXCEPTION = e;
    }

    public AgriPrpallPlatformService_Service() {
        super(__getWsdlLocation(), AGRIPRPALLPLATFORMSERVICE_QNAME);
    }

    public AgriPrpallPlatformService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGRIPRPALLPLATFORMSERVICE_QNAME, features);
    }

    public AgriPrpallPlatformService_Service(URL wsdlLocation) {
        super(wsdlLocation, AGRIPRPALLPLATFORMSERVICE_QNAME);
    }

    public AgriPrpallPlatformService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGRIPRPALLPLATFORMSERVICE_QNAME, features);
    }

    public AgriPrpallPlatformService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgriPrpallPlatformService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgriPrpallPlatformService
     */
    @WebEndpoint(name = "AgriPrpallPlatformService")
    public AgriPrpallPlatformService getAgriPrpallPlatformService() {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallPlatformService"), AgriPrpallPlatformService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgriPrpallPlatformService
     */
    @WebEndpoint(name = "AgriPrpallPlatformService")
    public AgriPrpallPlatformService getAgriPrpallPlatformService(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallPlatformService"), AgriPrpallPlatformService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGRIPRPALLPLATFORMSERVICE_EXCEPTION!= null) {
            throw AGRIPRPALLPLATFORMSERVICE_EXCEPTION;
        }
        return AGRIPRPALLPLATFORMSERVICE_WSDL_LOCATION;
    }

}
