
package com.sinosoft.agriprpall.api.client.undwrttrace;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgriPrpallUndwrtTraceInfoService", targetNamespace = "http://server.webservice.indiv.sinosoft.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgriPrpallUndwrtTraceInfoService {


    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "queryUndwrtTraceInfoReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "queryUndwrtTraceInfo", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.QueryUndwrtTraceInfo")
    @ResponseWrapper(localName = "queryUndwrtTraceInfoResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.QueryUndwrtTraceInfoResponse")
    public String queryUndwrtTraceInfo(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

    /**
     * 
     * @param businessNo
     * @return
     *     returns com.sinosoft.demo.core.webservice.ArrayOfXsdAnyType
     */
    @WebMethod
    @WebResult(name = "getTraceInfoListReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "getTraceInfoList", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.GetTraceInfoList")
    @ResponseWrapper(localName = "getTraceInfoListResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.GetTraceInfoListResponse")
    public ArrayOfXsdAnyType getTraceInfoList(
            @WebParam(name = "BusinessNo", targetNamespace = "http://webservices.sinosoft.com")
                    String businessNo);

}
