
package com.sinosoft.agriprpall.api.client.undwrttrace;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgriPrpallUndwrtTraceInfoService", targetNamespace = "http://server.webservice.indiv.sinosoft.com", wsdlLocation = "http://192.168.0.84:7001/webAgriPrpallService/services/AgriPrpallUndwrtTraceInfoService?wsdl")
public class AgriPrpallUndwrtTraceInfoService_Service
    extends Service
{

    private final static URL AGRIPRPALLUNDWRTTRACEINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException AGRIPRPALLUNDWRTTRACEINFOSERVICE_EXCEPTION;
    private final static QName AGRIPRPALLUNDWRTTRACEINFOSERVICE_QNAME = new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallUndwrtTraceInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.84:7001/webAgriPrpallService/services/AgriPrpallUndwrtTraceInfoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGRIPRPALLUNDWRTTRACEINFOSERVICE_WSDL_LOCATION = url;
        AGRIPRPALLUNDWRTTRACEINFOSERVICE_EXCEPTION = e;
    }

    public AgriPrpallUndwrtTraceInfoService_Service() {
        super(__getWsdlLocation(), AGRIPRPALLUNDWRTTRACEINFOSERVICE_QNAME);
    }

    public AgriPrpallUndwrtTraceInfoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGRIPRPALLUNDWRTTRACEINFOSERVICE_QNAME, features);
    }

    public AgriPrpallUndwrtTraceInfoService_Service(URL wsdlLocation) {
        super(wsdlLocation, AGRIPRPALLUNDWRTTRACEINFOSERVICE_QNAME);
    }

    public AgriPrpallUndwrtTraceInfoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGRIPRPALLUNDWRTTRACEINFOSERVICE_QNAME, features);
    }

    public AgriPrpallUndwrtTraceInfoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgriPrpallUndwrtTraceInfoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgriPrpallUndwrtTraceInfoService
     */
    @WebEndpoint(name = "AgriPrpallUndwrtTraceInfoService")
    public AgriPrpallUndwrtTraceInfoService getAgriPrpallUndwrtTraceInfoService() {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallUndwrtTraceInfoService"), AgriPrpallUndwrtTraceInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgriPrpallUndwrtTraceInfoService
     */
    @WebEndpoint(name = "AgriPrpallUndwrtTraceInfoService")
    public AgriPrpallUndwrtTraceInfoService getAgriPrpallUndwrtTraceInfoService(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallUndwrtTraceInfoService"), AgriPrpallUndwrtTraceInfoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGRIPRPALLUNDWRTTRACEINFOSERVICE_EXCEPTION!= null) {
            throw AGRIPRPALLUNDWRTTRACEINFOSERVICE_EXCEPTION;
        }
        return AGRIPRPALLUNDWRTTRACEINFOSERVICE_WSDL_LOCATION;
    }

}
