
package com.sinosoft.agriprpall.api.client.visaclient;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgriPrpallVisaService", targetNamespace = "http://server.webservice.indiv.sinosoft.com", wsdlLocation = "http://192.168.0.69:7001/webAgriPrpallService/services/AgriPrpallVisaService?wsdl")
public class AgriPrpallVisaService_Service
        extends Service {

    private final static URL AGRIPRPALLVISASERVICE_WSDL_LOCATION;
    private final static WebServiceException AGRIPRPALLVISASERVICE_EXCEPTION;
    private final static QName AGRIPRPALLVISASERVICE_QNAME = new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallVisaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.69:7001/webAgriPrpallService/services/AgriPrpallVisaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGRIPRPALLVISASERVICE_WSDL_LOCATION = url;
        AGRIPRPALLVISASERVICE_EXCEPTION = e;
    }

    public AgriPrpallVisaService_Service() {
        super(__getWsdlLocation(), AGRIPRPALLVISASERVICE_QNAME);
    }

    public AgriPrpallVisaService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGRIPRPALLVISASERVICE_QNAME, features);
    }

    public AgriPrpallVisaService_Service(URL wsdlLocation) {
        super(wsdlLocation, AGRIPRPALLVISASERVICE_QNAME);
    }

    public AgriPrpallVisaService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGRIPRPALLVISASERVICE_QNAME, features);
    }

    public AgriPrpallVisaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgriPrpallVisaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgriPrpallVisaService
     */
    @WebEndpoint(name = "AgriPrpallVisaService")
    public AgriPrpallVisaService getAgriPrpallVisaService() {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallVisaService"), AgriPrpallVisaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgriPrpallVisaService
     */
    @WebEndpoint(name = "AgriPrpallVisaService")
    public AgriPrpallVisaService getAgriPrpallVisaService(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallVisaService"), AgriPrpallVisaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGRIPRPALLVISASERVICE_EXCEPTION != null) {
            throw AGRIPRPALLVISASERVICE_EXCEPTION;
        }
        return AGRIPRPALLVISASERVICE_WSDL_LOCATION;
    }

}
