
package com.sinosoft.agriprpall.api.client.visaclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgriPrpallVisaService", targetNamespace = "http://server.webservice.indiv.sinosoft.com")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface AgriPrpallVisaService {


    /**
     * @param requestXML
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "trashTransReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "trashTrans", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.TrashTrans")
    @ResponseWrapper(localName = "trashTransResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.TrashTransResponse")
    public String trashTrans(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "queryVisaserialnoReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "queryVisaserialno", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.QueryVisaserialno")
    @ResponseWrapper(localName = "queryVisaserialnoResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.QueryVisaserialnoResponse")
    public String queryVisaserialno(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "visaStatusWriteBackReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "visaStatusWriteBack", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.VisaStatusWriteBack")
    @ResponseWrapper(localName = "visaStatusWriteBackResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.VisaStatusWriteBackResponse")
    public String visaStatusWriteBack(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "queryVisaCodesAndVisaSerialNosReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "queryVisaCodesAndVisaSerialNos", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.QueryVisaCodesAndVisaSerialNos")
    @ResponseWrapper(localName = "queryVisaCodesAndVisaSerialNosResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.QueryVisaCodesAndVisaSerialNosResponse")
    public String queryVisaCodesAndVisaSerialNos(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "querysVisaCodesAndVisaSerialNosReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "querysVisaCodesAndVisaSerialNos", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.QuerysVisaCodesAndVisaSerialNos")
    @ResponseWrapper(localName = "querysVisaCodesAndVisaSerialNosResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.QuerysVisaCodesAndVisaSerialNosResponse")
    public String querysVisaCodesAndVisaSerialNos(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "queryVisaCodeReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "queryVisaCode", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.QueryVisaCode")
    @ResponseWrapper(localName = "queryVisaCodeResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.QueryVisaCodeResponse")
    public String queryVisaCode(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

}
