
package com.sinosoft.agriclaim.core.common.undwrtClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NewAgriPrpallUndwrtService", targetNamespace = "http://server.webservice.indiv.sinosoft.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NewAgriPrpallUndwrtService {


    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "underwriteSubmitReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "underwriteSubmit", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.undwrtClient.UnderwriteSubmit")
    @ResponseWrapper(localName = "underwriteSubmitResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.undwrtClient.UnderwriteSubmitResponse")
    public String underwriteSubmit(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML)
        throws Exception_Exception
    ;

    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "reCaseSubmitReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "reCaseSubmit", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.undwrtClient.ReCaseSubmit")
    @ResponseWrapper(localName = "reCaseSubmitResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.undwrtClient.ReCaseSubmitResponse")
    public String reCaseSubmit(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "compensateSubmitReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "compensateSubmit", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.undwrtClient.CompensateSubmit")
    @ResponseWrapper(localName = "compensateSubmitResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.undwrtClient.CompensateSubmitResponse")
    public String compensateSubmit(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "prepaySubmitReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "prepaySubmit", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.undwrtClient.PrepaySubmit")
    @ResponseWrapper(localName = "prepaySubmitResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.undwrtClient.PrepaySubmitResponse")
    public String prepaySubmit(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "claimPaySubmitReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "claimPaySubmit", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.undwrtClient.ClaimPaySubmit")
    @ResponseWrapper(localName = "claimPaySubmitResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.undwrtClient.ClaimPaySubmitResponse")
    public String claimPaySubmit(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "queryCommonTraceInfoReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "queryCommonTraceInfo", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.undwrtClient.QueryCommonTraceInfo")
    @ResponseWrapper(localName = "queryCommonTraceInfoResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.undwrtClient.QueryCommonTraceInfoResponse")
    public String queryCommonTraceInfo(
            @WebParam(name = "xml", targetNamespace = "http://webservices.sinosoft.com")
                    String xml);

}
