management:
    security:
        enabled: true
#    context-path: /mng

spring:
    boot:
        admin:
#            username: "${security.user.name}"
#            password: "${security.user.password}"
#            client:
#                metadata:
#                    user.name: "${security.user.name}"
#                    user.password: "${security.user.password}"
#            auto-registration: true
            discovery:
                enabled: true
                services: ${config.admin.services:gateway,agriclaim,agriprpall,notice,txnlist,uap,ims,dms,pms,sso}
#                converter:
#                    management-context-path: /mng
#                    health-endpoint-path: /mng/health
            turbine:
                enabled: true
                clusters: default
                location: turbine
            hazelcast:
                enabled: true
            routes:
                endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti

security:
    basic:
        enabled: true
    user:
        name: admin
        password: admin123

logging:
    level:
        root: info
        org.springframework.security: debug

zuul.sensitiveHeaders: