
package com.sinosoft.demo.core.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NewAgriPrpallService", targetNamespace = "http://server_second.webservice.indiv.sinosoft.com", wsdlLocation = "http://192.168.0.175:7001/undwrt/services/NewAgriPrpallService?wsdl")
public class NewAgriPrpallService_Service
    extends Service
{

    private final static URL NEWAGRIPRPALLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NEWAGRIPRPALLSERVICE_EXCEPTION;
    private final static QName NEWAGRIPRPALLSERVICE_QNAME = new QName("http://server_second.webservice.indiv.sinosoft.com", "NewAgriPrpallService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.175:7001/undwrt/services/NewAgriPrpallService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NEWAGRIPRPALLSERVICE_WSDL_LOCATION = url;
        NEWAGRIPRPALLSERVICE_EXCEPTION = e;
    }

    public NewAgriPrpallService_Service() {
        super(__getWsdlLocation(), NEWAGRIPRPALLSERVICE_QNAME);
    }

    public NewAgriPrpallService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NEWAGRIPRPALLSERVICE_QNAME, features);
    }

    public NewAgriPrpallService_Service(URL wsdlLocation) {
        super(wsdlLocation, NEWAGRIPRPALLSERVICE_QNAME);
    }

    public NewAgriPrpallService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NEWAGRIPRPALLSERVICE_QNAME, features);
    }

    public NewAgriPrpallService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NewAgriPrpallService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NewAgriPrpallService
     */
    @WebEndpoint(name = "NewAgriPrpallService")
    public NewAgriPrpallService getNewAgriPrpallService() {
        return super.getPort(new QName("http://server_second.webservice.indiv.sinosoft.com", "NewAgriPrpallService"), NewAgriPrpallService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NewAgriPrpallService
     */
    @WebEndpoint(name = "NewAgriPrpallService")
    public NewAgriPrpallService getNewAgriPrpallService(WebServiceFeature... features) {
        return super.getPort(new QName("http://server_second.webservice.indiv.sinosoft.com", "NewAgriPrpallService"), NewAgriPrpallService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NEWAGRIPRPALLSERVICE_EXCEPTION!= null) {
            throw NEWAGRIPRPALLSERVICE_EXCEPTION;
        }
        return NEWAGRIPRPALLSERVICE_WSDL_LOCATION;
    }

}
