logging:
    level:
        root: INFO
#        org.springframework.web.servlet.DispatcherServlet: DEBUG
        com.sinosoft: info
        druid.sql: info

#swagger.exclude-path: /error,/ops/**,/mng/**
swagger.show: true
swagger.api.basepackage: com.sinosoft.ims.web
swagger.api.title: ims-APIs
swagger.api.description: 权限管理系统API
swagger.api.version: 1.0
