
package com.sinosoft.framework.agri.core.seal.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.15
 * 2018-01-25T14:11:42.493+08:00
 * Generated source version: 2.7.15
 */

@WebFault(name = "Exception", targetNamespace = "http://serv")
public class Exception_Exception extends java.lang.Exception {
    
    private com.sinosoft.framework.agri.core.seal.webservice.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.sinosoft.framework.agri.core.seal.webservice.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.sinosoft.framework.agri.core.seal.webservice.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.sinosoft.framework.agri.core.seal.webservice.Exception getFaultInfo() {
        return this.exception;
    }
}
