package com.sinosoft.framework.agri.core.seal.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2018-01-25T14:11:42.878+08:00
 * Generated source version: 2.7.15
 * 
 */
@WebServiceClient(name = "SealService", 
                  wsdlLocation = "http://192.168.0.118:99/SealServicewsdl.txt",
                  targetNamespace = "http://serv") 
public class SealService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://serv", "SealService");
    public final static QName SealServiceHttpEndpoint = new QName("http://serv", "SealServiceHttpEndpoint");
    public final static QName SealServiceHttpSoap11Endpoint = new QName("http://serv", "SealServiceHttpSoap11Endpoint");
    public final static QName SealServiceHttpSoap12Endpoint = new QName("http://serv", "SealServiceHttpSoap12Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.118:99/SealServicewsdl.txt");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SealService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.118:99/SealServicewsdl.txt");
        }
        WSDL_LOCATION = url;
    }

    public SealService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SealService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SealService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SealService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SealService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SealService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SealServicePortType
     */
    @WebEndpoint(name = "SealServiceHttpEndpoint")
    public SealServicePortType getSealServiceHttpEndpoint() {
        return super.getPort(SealServiceHttpEndpoint, SealServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SealServicePortType
     */
    @WebEndpoint(name = "SealServiceHttpEndpoint")
    public SealServicePortType getSealServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(SealServiceHttpEndpoint, SealServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns SealServicePortType
     */
    @WebEndpoint(name = "SealServiceHttpSoap11Endpoint")
    public SealServicePortType getSealServiceHttpSoap11Endpoint() {
        return super.getPort(SealServiceHttpSoap11Endpoint, SealServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SealServicePortType
     */
    @WebEndpoint(name = "SealServiceHttpSoap11Endpoint")
    public SealServicePortType getSealServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(SealServiceHttpSoap11Endpoint, SealServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns SealServicePortType
     */
    @WebEndpoint(name = "SealServiceHttpSoap12Endpoint")
    public SealServicePortType getSealServiceHttpSoap12Endpoint() {
        return super.getPort(SealServiceHttpSoap12Endpoint, SealServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SealServicePortType
     */
    @WebEndpoint(name = "SealServiceHttpSoap12Endpoint")
    public SealServicePortType getSealServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(SealServiceHttpSoap12Endpoint, SealServicePortType.class, features);
    }

}
