
package com.sinosoft.agriprpall.api.client.paymentclient;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "AgriPrpallQueryAndDeleteExchangeInfoService", targetNamespace = "http://server.webservice.indiv.sinosoft.com", wsdlLocation = "http://192.168.0.42:7001/webAgriPrpallService/services/AgriPrpallQueryAndDeleteExchangeInfoService?wsdl")
public class AgriPrpallQueryAndDeleteExchangeInfoService_Service
        extends Service {

    private final static URL AGRIPRPALLQUERYANDDELETEEXCHANGEINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException AGRIPRPALLQUERYANDDELETEEXCHANGEINFOSERVICE_EXCEPTION;
    private final static QName AGRIPRPALLQUERYANDDELETEEXCHANGEINFOSERVICE_QNAME = new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallQueryAndDeleteExchangeInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.42:7001/webAgriPrpallService/services/AgriPrpallQueryAndDeleteExchangeInfoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGRIPRPALLQUERYANDDELETEEXCHANGEINFOSERVICE_WSDL_LOCATION = url;
        AGRIPRPALLQUERYANDDELETEEXCHANGEINFOSERVICE_EXCEPTION = e;
    }

    public AgriPrpallQueryAndDeleteExchangeInfoService_Service() {
        super(__getWsdlLocation(), AGRIPRPALLQUERYANDDELETEEXCHANGEINFOSERVICE_QNAME);
    }

    public AgriPrpallQueryAndDeleteExchangeInfoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGRIPRPALLQUERYANDDELETEEXCHANGEINFOSERVICE_QNAME, features);
    }

    public AgriPrpallQueryAndDeleteExchangeInfoService_Service(URL wsdlLocation) {
        super(wsdlLocation, AGRIPRPALLQUERYANDDELETEEXCHANGEINFOSERVICE_QNAME);
    }

    public AgriPrpallQueryAndDeleteExchangeInfoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGRIPRPALLQUERYANDDELETEEXCHANGEINFOSERVICE_QNAME, features);
    }

    public AgriPrpallQueryAndDeleteExchangeInfoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgriPrpallQueryAndDeleteExchangeInfoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns AgriPrpallQueryAndDeleteExchangeInfoService
     */
    @WebEndpoint(name = "AgriPrpallQueryAndDeleteExchangeInfoService")
    public AgriPrpallQueryAndDeleteExchangeInfoService getAgriPrpallQueryAndDeleteExchangeInfoService() {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallQueryAndDeleteExchangeInfoService"), AgriPrpallQueryAndDeleteExchangeInfoService.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns AgriPrpallQueryAndDeleteExchangeInfoService
     */
    @WebEndpoint(name = "AgriPrpallQueryAndDeleteExchangeInfoService")
    public AgriPrpallQueryAndDeleteExchangeInfoService getAgriPrpallQueryAndDeleteExchangeInfoService(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallQueryAndDeleteExchangeInfoService"), AgriPrpallQueryAndDeleteExchangeInfoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGRIPRPALLQUERYANDDELETEEXCHANGEINFOSERVICE_EXCEPTION != null) {
            throw AGRIPRPALLQUERYANDDELETEEXCHANGEINFOSERVICE_EXCEPTION;
        }
        return AGRIPRPALLQUERYANDDELETEEXCHANGEINFOSERVICE_WSDL_LOCATION;
    }

}
