
package com.sinosoft.agriprpall.api.client.paymentclient;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "AgriPrpallRepolicynoInfoService", targetNamespace = "http://server.webservice.indiv.sinosoft.com", wsdlLocation = "http://192.168.0.84:7001/webAgriPrpallService/services/AgriPrpallRepolicynoInfoService?wsdl")
public class AgriPrpallRepolicynoInfoService_Service
        extends Service {

    private final static URL AGRIPRPALLREPOLICYNOINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException AGRIPRPALLREPOLICYNOINFOSERVICE_EXCEPTION;
    private final static QName AGRIPRPALLREPOLICYNOINFOSERVICE_QNAME = new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallRepolicynoInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.84:7001/webAgriPrpallService/services/AgriPrpallRepolicynoInfoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGRIPRPALLREPOLICYNOINFOSERVICE_WSDL_LOCATION = url;
        AGRIPRPALLREPOLICYNOINFOSERVICE_EXCEPTION = e;
    }

    public AgriPrpallRepolicynoInfoService_Service() {
        super(__getWsdlLocation(), AGRIPRPALLREPOLICYNOINFOSERVICE_QNAME);
    }

    public AgriPrpallRepolicynoInfoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGRIPRPALLREPOLICYNOINFOSERVICE_QNAME, features);
    }

    public AgriPrpallRepolicynoInfoService_Service(URL wsdlLocation) {
        super(wsdlLocation, AGRIPRPALLREPOLICYNOINFOSERVICE_QNAME);
    }

    public AgriPrpallRepolicynoInfoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGRIPRPALLREPOLICYNOINFOSERVICE_QNAME, features);
    }

    public AgriPrpallRepolicynoInfoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgriPrpallRepolicynoInfoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns AgriPrpallRepolicynoInfoService
     */
    @WebEndpoint(name = "AgriPrpallRepolicynoInfoService")
    public AgriPrpallRepolicynoInfoService getAgriPrpallRepolicynoInfoService() {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallRepolicynoInfoService"), AgriPrpallRepolicynoInfoService.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns AgriPrpallRepolicynoInfoService
     */
    @WebEndpoint(name = "AgriPrpallRepolicynoInfoService")
    public AgriPrpallRepolicynoInfoService getAgriPrpallRepolicynoInfoService(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallRepolicynoInfoService"), AgriPrpallRepolicynoInfoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGRIPRPALLREPOLICYNOINFOSERVICE_EXCEPTION != null) {
            throw AGRIPRPALLREPOLICYNOINFOSERVICE_EXCEPTION;
        }
        return AGRIPRPALLREPOLICYNOINFOSERVICE_WSDL_LOCATION;
    }

}
