
package com.sinosoft.agriprpall.api.client.changepassword;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "AgriPrpallSelfQueryService", targetNamespace = "http://server.webservice.indiv.sinosoft.com", wsdlLocation = "http://192.168.0.2:7701/webAgriPrpallService/services/AgriPrpallSelfQueryService?wsdl")
public class AgriPrpallSelfQueryService_Service
        extends Service {

    private final static URL AGRIPRPALLSELFQUERYSERVICE_WSDL_LOCATION;
    private final static WebServiceException AGRIPRPALLSELFQUERYSERVICE_EXCEPTION;
    private final static QName AGRIPRPALLSELFQUERYSERVICE_QNAME = new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallSelfQueryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.2:7701/webAgriPrpallService/services/AgriPrpallSelfQueryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGRIPRPALLSELFQUERYSERVICE_WSDL_LOCATION = url;
        AGRIPRPALLSELFQUERYSERVICE_EXCEPTION = e;
    }

    public AgriPrpallSelfQueryService_Service() {
        super(__getWsdlLocation(), AGRIPRPALLSELFQUERYSERVICE_QNAME);
    }

    public AgriPrpallSelfQueryService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGRIPRPALLSELFQUERYSERVICE_QNAME, features);
    }

    public AgriPrpallSelfQueryService_Service(URL wsdlLocation) {
        super(wsdlLocation, AGRIPRPALLSELFQUERYSERVICE_QNAME);
    }

    public AgriPrpallSelfQueryService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGRIPRPALLSELFQUERYSERVICE_QNAME, features);
    }

    public AgriPrpallSelfQueryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgriPrpallSelfQueryService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns AgriPrpallSelfQueryService
     */
    @WebEndpoint(name = "AgriPrpallVisaService")
    public AgriPrpallSelfQueryService getAgriPrpallVisaService() {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallVisaService"), AgriPrpallSelfQueryService.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns AgriPrpallSelfQueryService
     */
    @WebEndpoint(name = "AgriPrpallVisaService")
    public AgriPrpallSelfQueryService getAgriPrpallVisaService(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallVisaService"), AgriPrpallSelfQueryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGRIPRPALLSELFQUERYSERVICE_EXCEPTION != null) {
            throw AGRIPRPALLSELFQUERYSERVICE_EXCEPTION;
        }
        return AGRIPRPALLSELFQUERYSERVICE_WSDL_LOCATION;
    }

}
