
package com.sinosoft.agriprpall.api.client.rinsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgriPrpallReinsService", targetNamespace = "http://server.webservice.indiv.sinosoft.com", wsdlLocation = "http://192.168.0.136:7001/webAgriPrpallService/services/AgriPrpallReinsService?wsdl")
public class AgriPrpallReinsService_Service
    extends Service
{

    private final static URL AGRIPRPALLREINSSERVICE_WSDL_LOCATION;
    private final static WebServiceException AGRIPRPALLREINSSERVICE_EXCEPTION;
    private final static QName AGRIPRPALLREINSSERVICE_QNAME = new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallReinsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.136:7001/webAgriPrpallService/services/AgriPrpallReinsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGRIPRPALLREINSSERVICE_WSDL_LOCATION = url;
        AGRIPRPALLREINSSERVICE_EXCEPTION = e;
    }

    public AgriPrpallReinsService_Service() {
        super(__getWsdlLocation(), AGRIPRPALLREINSSERVICE_QNAME);
    }

    public AgriPrpallReinsService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGRIPRPALLREINSSERVICE_QNAME, features);
    }

    public AgriPrpallReinsService_Service(URL wsdlLocation) {
        super(wsdlLocation, AGRIPRPALLREINSSERVICE_QNAME);
    }

    public AgriPrpallReinsService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGRIPRPALLREINSSERVICE_QNAME, features);
    }

    public AgriPrpallReinsService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgriPrpallReinsService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgriPrpallReinsService
     */
    @WebEndpoint(name = "AgriPrpallReinsService")
    public AgriPrpallReinsService getAgriPrpallReinsService() {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallReinsService"), AgriPrpallReinsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgriPrpallReinsService
     */
    @WebEndpoint(name = "AgriPrpallReinsService")
    public AgriPrpallReinsService getAgriPrpallReinsService(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallReinsService"), AgriPrpallReinsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGRIPRPALLREINSSERVICE_EXCEPTION!= null) {
            throw AGRIPRPALLREINSSERVICE_EXCEPTION;
        }
        return AGRIPRPALLREINSSERVICE_WSDL_LOCATION;
    }

}
