
package com.sinosoft.agriprpall.api.client.rinsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgriPrpallReinsService", targetNamespace = "http://server.webservice.indiv.sinosoft.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgriPrpallReinsService {


    /**
     * 
     * @param recivexml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getNewAgriPrpallReinsReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "getNewAgriPrpallReins", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.GetNewAgriPrpallReins")
    @ResponseWrapper(localName = "getNewAgriPrpallReinsResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.GetNewAgriPrpallReinsResponse")
    public String getNewAgriPrpallReins(
            @WebParam(name = "recivexml", targetNamespace = "http://webservices.sinosoft.com")
                    String recivexml);

    /**
     * 
     * @param recivexml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getReinsCoinsuranceAgreementReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "getReinsCoinsuranceAgreement", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.GetReinsCoinsuranceAgreement")
    @ResponseWrapper(localName = "getReinsCoinsuranceAgreementResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.GetReinsCoinsuranceAgreementResponse")
    public String getReinsCoinsuranceAgreement(
            @WebParam(name = "recivexml", targetNamespace = "http://webservices.sinosoft.com")
                    String recivexml);

    /**
     * 
     * @param recivexml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getReinsAgreementReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "getReinsAgreement", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.GetReinsAgreement")
    @ResponseWrapper(localName = "getReinsAgreementResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.GetReinsAgreementResponse")
    public String getReinsAgreement(
            @WebParam(name = "recivexml", targetNamespace = "http://webservices.sinosoft.com")
                    String recivexml);

}
