
package com.sinosoft.agriprpall.api.client.rinsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgriPrpallTerroristInfoService", targetNamespace = "http://server.webservice.indiv.sinosoft.com", wsdlLocation = "http://192.168.0.84:7001/webAgriPrpallService/services/AgriPrpallTerroristInfoService?wsdl")
public class AgriPrpallTerroristInfoService_Service
    extends Service
{

    private final static URL AGRIPRPALLTERRORISTINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException AGRIPRPALLTERRORISTINFOSERVICE_EXCEPTION;
    private final static QName AGRIPRPALLTERRORISTINFOSERVICE_QNAME = new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallTerroristInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.84:7001/webAgriPrpallService/services/AgriPrpallTerroristInfoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGRIPRPALLTERRORISTINFOSERVICE_WSDL_LOCATION = url;
        AGRIPRPALLTERRORISTINFOSERVICE_EXCEPTION = e;
    }

    public AgriPrpallTerroristInfoService_Service() {
        super(__getWsdlLocation(), AGRIPRPALLTERRORISTINFOSERVICE_QNAME);
    }

    public AgriPrpallTerroristInfoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGRIPRPALLTERRORISTINFOSERVICE_QNAME, features);
    }

    public AgriPrpallTerroristInfoService_Service(URL wsdlLocation) {
        super(wsdlLocation, AGRIPRPALLTERRORISTINFOSERVICE_QNAME);
    }

    public AgriPrpallTerroristInfoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGRIPRPALLTERRORISTINFOSERVICE_QNAME, features);
    }

    public AgriPrpallTerroristInfoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgriPrpallTerroristInfoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgriPrpallTerroristInfoService
     */
    @WebEndpoint(name = "AgriPrpallTerroristInfoService")
    public AgriPrpallTerroristInfoService getAgriPrpallTerroristInfoService() {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallTerroristInfoService"), AgriPrpallTerroristInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgriPrpallTerroristInfoService
     */
    @WebEndpoint(name = "AgriPrpallTerroristInfoService")
    public AgriPrpallTerroristInfoService getAgriPrpallTerroristInfoService(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallTerroristInfoService"), AgriPrpallTerroristInfoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGRIPRPALLTERRORISTINFOSERVICE_EXCEPTION!= null) {
            throw AGRIPRPALLTERRORISTINFOSERVICE_EXCEPTION;
        }
        return AGRIPRPALLTERRORISTINFOSERVICE_WSDL_LOCATION;
    }

}
