
package com.sinosoft.agriprpall.api.client.rinsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgriPrpallRelateRepolicynoService", targetNamespace = "http://server.webservice.indiv.sinosoft.com", wsdlLocation = "http://192.168.0.84:7001/webAgriPrpallService/services/AgriPrpallRelateRepolicynoService?wsdl")
public class AgriPrpallRelateRepolicynoService_Service
    extends Service
{

    private final static URL AGRIPRPALLRELATEREPOLICYNOSERVICE_WSDL_LOCATION;
    private final static WebServiceException AGRIPRPALLRELATEREPOLICYNOSERVICE_EXCEPTION;
    private final static QName AGRIPRPALLRELATEREPOLICYNOSERVICE_QNAME = new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallRelateRepolicynoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.84:7001/webAgriPrpallService/services/AgriPrpallRelateRepolicynoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGRIPRPALLRELATEREPOLICYNOSERVICE_WSDL_LOCATION = url;
        AGRIPRPALLRELATEREPOLICYNOSERVICE_EXCEPTION = e;
    }

    public AgriPrpallRelateRepolicynoService_Service() {
        super(__getWsdlLocation(), AGRIPRPALLRELATEREPOLICYNOSERVICE_QNAME);
    }

    public AgriPrpallRelateRepolicynoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGRIPRPALLRELATEREPOLICYNOSERVICE_QNAME, features);
    }

    public AgriPrpallRelateRepolicynoService_Service(URL wsdlLocation) {
        super(wsdlLocation, AGRIPRPALLRELATEREPOLICYNOSERVICE_QNAME);
    }

    public AgriPrpallRelateRepolicynoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGRIPRPALLRELATEREPOLICYNOSERVICE_QNAME, features);
    }

    public AgriPrpallRelateRepolicynoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgriPrpallRelateRepolicynoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgriPrpallRelateRepolicynoService
     */
    @WebEndpoint(name = "AgriPrpallRelateRepolicynoService")
    public AgriPrpallRelateRepolicynoService getAgriPrpallRelateRepolicynoService() {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallRelateRepolicynoService"), AgriPrpallRelateRepolicynoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgriPrpallRelateRepolicynoService
     */
    @WebEndpoint(name = "AgriPrpallRelateRepolicynoService")
    public AgriPrpallRelateRepolicynoService getAgriPrpallRelateRepolicynoService(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallRelateRepolicynoService"), AgriPrpallRelateRepolicynoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGRIPRPALLRELATEREPOLICYNOSERVICE_EXCEPTION!= null) {
            throw AGRIPRPALLRELATEREPOLICYNOSERVICE_EXCEPTION;
        }
        return AGRIPRPALLRELATEREPOLICYNOSERVICE_WSDL_LOCATION;
    }

}
