server:
    port: 8888
    #context-path: /dms-rest
spring:
    datasource:
        url: jdbc:oracle:thin:@192.168.0.2:1521:dhzbdev
        username: agri
        password: ${password}
        driver-class-name: oracle.jdbc.OracleDriver
        type: com.alibaba.druid.pool.DruidDataSource
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化大小，最小，最大
        initialSize: 1
        minIdle: 3
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 30000
#        validationQuery: select 'x'
        validationQuery: select 1 from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j,config
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${publicKey}

ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 5000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000


#privateKey: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAhOUfqExWrYexVLq6/3HVeFsGiLWPNt8TnDwOoz2janOkBhDakgMUJ45Wd4O84S1PiE3R1fu4wrPmj0PKaOdHAwIDAQABAkABcRbp1YIvOcSjva7frJV7S8mDXCzklID69e/Wt4l5UynKmmQGMJE2cc50r6MtlAtII2QeK7drBVFKWuRlOyrpAiEA2dxJD65b6+mRNhF1moHMMKm6/yES5rNSulFZ3fIdwKUCIQCcKP6nwTwTWslQeAZDD13uMjlv2VW0oUwtcJ2ufWzwhwIhANhgvMPxVeTKl2oPDzIFBouymEJ7U+2EX38j+1C//yLtAiBCLeVuNqg9E5aJcbRFqzeFgOdyjUqTGGBuSXGpxyHp9QIgf/Chvif/6llbSzQdi6tiKeWIuGI0EDmiO2S0uNgI9jY=
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAITlH6hMVq2HsVS6uv9x1XhbBoi1jzbfE5w8DqM9o2pzpAYQ2pIDFCeOVneDvOEtT4hN0dX7uMKz5o9DymjnRwMCAwEAAQ==
password: Lwj7cjE9iVz6LBkIjp40qKG0jEboph828Ee9fV7JwjhA20uaxQ2Tga90BvsuFPwFqhSeoWPbfhamL4XGo2Wqsw==

sm2:
  pubk: 044B3517B9DBC03DCF37C06614DFF202070F8A5E357DB4A1204C121DADFCCD4E36D3E4A8B8E1FC1367A33266709A795EA6D7B80F0BE43366E8ACB99CF09C276EAF
  prik: 00D541CC8586DB3587648A55CDFBD3E3532B734773F2ACE641192D220C9346A73E
webservice:
  prpallurl: http://192.168.0.175:7001/undwrt/services/NewAgriPrpallService?wsdl