
package com.sinosoft.agriprpall.api.client.undwrtclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgriPrpallUndwrtService", targetNamespace = "http://server.webservice.indiv.sinosoft.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgriPrpallUndwrtService {


    /**
     * 
     * @param requestXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "underwriteSubmitReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "underwriteSubmit", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.UnderwriteSubmit")
    @ResponseWrapper(localName = "underwriteSubmitResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.demo.core.webservice.UnderwriteSubmitResponse")
    public String underwriteSubmit(
            @WebParam(name = "requestXML", targetNamespace = "http://webservices.sinosoft.com")
                    String requestXML);

    /**
     *（重开赔案申请提交）
     * @param requestXML
     * @return
     * @Author 王志文
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "reCaseSubmitReturn", targetNamespace = "http://service.webservice.newagriprpall.sinosoft.com")
    @RequestWrapper(localName = "reCaseSubmit", targetNamespace = "http://service.webservice.newagriprpall.sinosoft.com", className = "com.sinosoft.demo.core.webservice.reCaseSubmit")
    @ResponseWrapper(localName = "reCaseSubmitResponse", targetNamespace = "http://service.webservice.newagriprpall.sinosoft.com", className = "com.sinosoft.demo.core.webservice.reCaseSubmitResponse")
    public String reCaseSubmit(
            @WebParam(name = "requestXML", targetNamespace = "http://service.webservice.newagriprpall.sinosoft.com")
                    String requestXML);

}
