
package com.sinosoft.agriprpall.api.client.undwrtclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgriPrpallUndwrtDeleteEndorseService", targetNamespace = "http://server.webservice.indiv.sinosoft.com", wsdlLocation = "http://192.168.0.84:7001/webAgriPrpallService/services/AgriPrpallUndwrtDeleteEndorseService?wsdl")
public class AgriPrpallUndwrtDeleteEndorseService_Service
    extends Service
{

    private final static URL AGRIPRPALLUNDWRTDELETEENDORSESERVICE_WSDL_LOCATION;
    private final static WebServiceException AGRIPRPALLUNDWRTDELETEENDORSESERVICE_EXCEPTION;
    private final static QName AGRIPRPALLUNDWRTDELETEENDORSESERVICE_QNAME = new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallUndwrtDeleteEndorseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.84:7001/webAgriPrpallService/services/AgriPrpallUndwrtDeleteEndorseService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGRIPRPALLUNDWRTDELETEENDORSESERVICE_WSDL_LOCATION = url;
        AGRIPRPALLUNDWRTDELETEENDORSESERVICE_EXCEPTION = e;
    }

    public AgriPrpallUndwrtDeleteEndorseService_Service() {
        super(__getWsdlLocation(), AGRIPRPALLUNDWRTDELETEENDORSESERVICE_QNAME);
    }

    public AgriPrpallUndwrtDeleteEndorseService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGRIPRPALLUNDWRTDELETEENDORSESERVICE_QNAME, features);
    }

    public AgriPrpallUndwrtDeleteEndorseService_Service(URL wsdlLocation) {
        super(wsdlLocation, AGRIPRPALLUNDWRTDELETEENDORSESERVICE_QNAME);
    }

    public AgriPrpallUndwrtDeleteEndorseService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGRIPRPALLUNDWRTDELETEENDORSESERVICE_QNAME, features);
    }

    public AgriPrpallUndwrtDeleteEndorseService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgriPrpallUndwrtDeleteEndorseService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgriPrpallUndwrtDeleteEndorseService
     */
    @WebEndpoint(name = "AgriPrpallUndwrtDeleteEndorseService")
    public AgriPrpallUndwrtDeleteEndorseService getAgriPrpallUndwrtDeleteEndorseService() {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallUndwrtDeleteEndorseService"), AgriPrpallUndwrtDeleteEndorseService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgriPrpallUndwrtDeleteEndorseService
     */
    @WebEndpoint(name = "AgriPrpallUndwrtDeleteEndorseService")
    public AgriPrpallUndwrtDeleteEndorseService getAgriPrpallUndwrtDeleteEndorseService(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.indiv.sinosoft.com", "AgriPrpallUndwrtDeleteEndorseService"), AgriPrpallUndwrtDeleteEndorseService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGRIPRPALLUNDWRTDELETEENDORSESERVICE_EXCEPTION!= null) {
            throw AGRIPRPALLUNDWRTDELETEENDORSESERVICE_EXCEPTION;
        }
        return AGRIPRPALLUNDWRTDELETEENDORSESERVICE_WSDL_LOCATION;
    }

}
