logging:
    level:
        root: INFO
#        org.springframework.web.servlet.DispatcherServlet: DEBUG
        com.sinosoft: DEBUG
        druid.sql: DEBUG

#swagger.exclude-path: /error,/ops/**,/mng/**
swagger.show: true
swagger.api.basepackage: com.sinosoft.agriprpall.web
swagger.api.title: agriprpall-APIs
swagger.api.description: 农险承保系统API
swagger.api.version: 1.0
