server:
    port: 9011
    #context-path: /dms-rest
spring:
    datasource:
        name: agriClaimDatasource
        url: jdbc:oracle:thin:@192.168.0.8:1521:agri
        driver-class-name: oracle.jdbc.OracleDriver
        username: gyic2
        password: ENC(L1YtArwku6pZMoVNGBXboDC1d1Pir9tw)
        connectionTimeout: 2000

ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 5000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000
#信雅达影像上传路径
IMAGE_CRUDT_URL: http://220.178.31.50:9200/SunECM/servlet/RouterServlet

paymentUrl: http://10.75.42.50:7003/payment/services/AgriClaimInterface?wsdl