server:
    port: 9010
    #context-path: /dms-rest
spring:
    datasource:
        name: agriPrpallDatasource
        url: jdbc:oracle:thin:@192.168.0.8:1521:agri
        driver-class-name: oracle.jdbc.OracleDriver
        username: gyic2
        #password: gyic_222
        password: ENC(1lE1D+OiOop/TCZsQsnE7kNBJMAGge7U)
        connectionTimeout: 2000

ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 5000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000


# 系统相关配置
sysconfig:
    # 公共配置
    common:
        #见费出单险种
        IS_SEE_FEE_RISK: 3101,3105,3107,3108,3114,3122,3125,3126,3149,3174,3177,3202,3220,3225

    # 保单模块
    policyManage:
        #正本限制
        editType:
            master: MASTER
            copy: COPY
        #缴费原因：自缴保费
        payReason: R10
        #缴费原因：政府补贴
        subsidy: RS3,RS4,RS5,RS6,RS7,PS3,PS4,PS5,PS6,PS7



