## 所有应用的公共配置
spring:
    redis:
        host: 192.168.0.5
        port: 6379
        #password: redis123
        password: ENC(AKLPygqZFEPgUt0xgVilBbrAmGmp8WhU)
        database: 0
        maxIdle: 300
        maxWait: 3000
        testOnBorrow: true
        expiration: 1800
    datasource:
        # druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            maxActive: 50      #最大连接池数 !生产要调整
            initialSize: 1     #初始连接池数 !生产要调整
            minIdle: 1         #最小连接池数 !生产要调整
            maxWait: 60000     #获取连接等待超时时间
            timeBetweenEvictionRunsMillis: 60000  #配置间隔多久才进行一次检测
            minEvictableIdleTimeMillis: 300000    #配置一个连接在池中最小生存的时间
            #validationQuery: select 'x'
            validationQuery: select 1 from dual
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
            # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
            filters: stat,slf4j
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
            # 合并多个DruidDataSource的监控数据
            useGlobalDataSourceStat: true
            stat-view-servlet:
                enabled: true
    jpa:
        database: ORACLE
        show-sql: true
        generate-ddl: false
        properties:
            hibernate:
                #dialect: org.hibernate.dialect.Oracle12cDialect  # 生产要调整
                dialect: org.hibernate.dialect.Oracle10gDialect  # 生产要调整
                physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    sleuth.sampler.percentage: 1.0

    zipkin:
        enabled: false
        locator.discovery.enabled: true
    rabbitmq:
        host: 192.168.0.7
        port: 5672
        username: rabbit
        password: rabbit

security.basic.enabled: false
security.user.name: admin
#security.user.password: admin123
security.user.password: ENC(6ewlR9pJ4vsag6dC8nbYROZTjwvu4PXm)
management:
    context-path: /mng
    security:
        enabled: true
        roles: SUPERUSER
eureka:
    instance:
        metadata-map:
            user.name: "${security.user.name}"    ## 用于服务端访问客户端
            user.password: "${security.user.password}"
            management.context-path: ${management.context-path}
filter:
  none:
    path: /api/auth,/api/autoAuth,/api/sso/api/autoAuth,/api/sso/api/auth,/api/status,/api/valid,/login,/api/logout,/js,/api/js,/css,/images,/mng,/fonts
token:
  maxAge: 172800
sso:
#    url: http://localhost:8089/sso
  url: http://192.168.0.5:9005/
front:
#    url: http://localhost:8089/frontend/index.html
  url: http://192.168.0.5:80/
#本地前端调试使用
localhost:
  url: http://localhost:99/
web:
#    url: http://localhost:8089/api/
    url: http://192.168.0.5:9000/



ssoApps:
    url: ${sso.url},${front.url},${localhost.url},${web.url},http://www.sinosoft-hf.cn:9005/,http://www.sinosoft-hf.cn:80/,http://www.sinosoft-hf.cn:9000/


# 周边接口对接配置信息
webservice:
    # 国元老核心相关系统服务配置
    webAgriPrpallService:
        url: http://192.168.0.2:7701 # 接口地址
        username: # 账号
        password: # 密码
    #金禾接口地址
    gycoreService:
      url: http://36.32.160.60:9000/GYCoreWebService.asmx?WSDL
#fileService地址
fileService:
  url: http://192.168.0.5:8080/fileserver-server
  url1: http://www.sinosoft-hf.cn:8088/fileserver-server
#导出Excel文件类型( 可选：.xls、.xlsx )
     # 种植险模板编号
  plantFileId: 2288dbf5051b44aa9b35ed86e4ce494a
     # 养殖险模板编号
  herdFileId: 98793181da944154b5027eabd763bd58
#导出Excel文件类型( 可选：.xls、.xlsx )
exportExcelType: .xls

# 系统相关配置
sysconfig:
    # 公共配置
    common:
        #新农险标识（mian表中的systemflag,用于区分新农险系统与老系统的数据）
        systemFlag: agri
    insureListRsk:
        # 清单存储在planting表的险种
        planting: 3107,3162,3155,3108
        # 清单存储在planting31表的险种
        planting31: 3141,3147
        # 清单存储在nyx表的险种
        nyx: 3224,3237,3130,3134,3129,3102
        # 清单存储在herd表的险种
        herd: 3220,3233
# log日志参数设置
logback:
    Path: /home/redhat/webapp-dev/logFiles #日志统一存储路径
    maxHistory: 7 #切分日志保留天数
#配置加密密钥
jasypt:
  encryptor:
    password: 9lWaL475Hqwg