server:
    port: 9006
    #context-path: /fileserver-rest

spring:
    datasource:
        name: fileserverDatasource
        url: jdbc:oracle:thin:@192.168.0.2:1521:dhzbdev
        driver-class-name: oracle.jdbc.OracleDriver
        username: agri
        password: agri
        connectionTimeout: 2000

ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 5000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000


