server:
  port: 9002
  #context-path: /ims-rest

spring:
    datasource:
        name: imsDatasource
        url: jdbc:oracle:thin:@192.168.0.8:1521:agri
        driver-class-name: oracle.jdbc.OracleDriver
        username: gyic2
        #password: gyic_222
        password: ENC(L1YtArwku6pZMoVNGBXboDC1d1Pir9tw)
        connectionTimeout: 2000

ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 5000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000

ims:
    ValiStatus: 1