server:
    port: 9008
    #context-path: /platform-rest
spring:
    datasource:
        name: platformDatasource
        url: jdbc:oracle:thin:@47.94.96.232:1521:xe
        driver-class-name: oracle.jdbc.OracleDriver
        username: SC_PLATFORM
        password: scplatform@yyjc
        connectionTimeout: 2000

ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 5000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000


