server:
    port: 9013
    #context-path: /dms-rest
spring:
    datasource:
        name: dmsDatasource
        url: jdbc:oracle:thin:@192.168.0.8:1521:agri
        driver-class-name: oracle.jdbc.OracleDriver
        username: txnlist2
#        password: txnlist1001
        password: ENC(0x9D+4obcgCkd3H1saiFeCR7KW8FVwcN)
        connectionTimeout: 2000
passssss: ENC(0x9D+4obcgCkd3H1saiFeCR7KW8FVwcN)
ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 5000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000


