server:
    port: 9012
    #context-path: /dms-rest
ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 5000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000


