
package com.sinosoft.agriclaim.core.common.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UIClaimPayService", targetNamespace = "http://server.webservice.indiv.sinosoft.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UIClaimPayService {


    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "queryPayListReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "queryPayList", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.client.QueryPayList")
    @ResponseWrapper(localName = "queryPayListResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.client.QueryPayListResponse")
    public String queryPayList(
            @WebParam(name = "xml", targetNamespace = "http://webservices.sinosoft.com")
                    String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "queryPayStatisticsListReturn", targetNamespace = "http://webservices.sinosoft.com")
    @RequestWrapper(localName = "queryPayStatisticsList", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.client.QueryPayStatisticsList")
    @ResponseWrapper(localName = "queryPayStatisticsListResponse", targetNamespace = "http://webservices.sinosoft.com", className = "com.sinosoft.agriclaim.core.common.client.QueryPayStatisticsListResponse")
    public String queryPayStatisticsList(
            @WebParam(name = "xml", targetNamespace = "http://webservices.sinosoft.com")
                    String xml);

}
