# 服务端口配置
server:
    port: 8000
spring:
    application:
        name: CONFIG-SERVER
    cloud:
        config:
            discovery:
                enabled: true
            server:
                default-label:
                native:
                    search-locations: ${PROPERTIES_PATH}
                    # 未避免生产环境读取不到环境变量使用默认值，出现配置错误，
                    # 所以不予配置默认值，开发人员可以配置环境变量或者使用下面的配置替换上线的配置
                    # search-locations: classpath:/repo
    profiles:
# 配置文件开关 svn
        active: native
eureka:
    client:
        serviceUrl:
            defaultZone: ${REGISTRY_URL:http://localhost:8001/eureka/}
        registry-fetch-interval-seconds: 30
    instance:
        lease-renewal-interval-in-seconds: 30
        preferIpAddress: true
        metadata-map:
            user: ${security.user.name}
            password: ${security.user.password}
        #  configPath: ${server.context-path}

security:
    user:
        name: config
        password: ENC(KuAm2K9gSI2+OjkXKSKn2NwCP6FBBpgB)

logging:
    level:
        org.springframework.cloud.config.server: DEBUG
        org.springframework.boot.env.PropertySourcesLoader: TRACE


#配置加密密钥
jasypt:
  encryptor:
    password: 9lWaL475Hqaa