logging:
    level:
        root: INFO
#        org.springframework.web.servlet.DispatcherServlet: DEBUG
        com.sinosoft: DEBUG
        druid.sql: DEBUG
    test: xxxxxx

#swagger.exclude-path: /error,/ops/**,/mng/**
swagger.show: true
swagger.api.basepackage: com.sinosoft.demo.web
swagger.api.title: demo-APIs
swagger.api.description: 农险 demo API
swagger.api.version: 1.0